# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cobaltspeech.bluehenge.v1 import bluehenge_pb2 as cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2


class BluehengeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Version = channel.unary_unary(
                '/cobaltspeech.bluehenge.v1.BluehengeService/Version',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.VersionRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.VersionResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/cobaltspeech.bluehenge.v1.BluehengeService/ListModels',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/cobaltspeech.bluehenge.v1.BluehengeService/CreateSession',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/cobaltspeech.bluehenge.v1.BluehengeService/DeleteSession',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)
        self.UpdateSession = channel.unary_unary(
                '/cobaltspeech.bluehenge.v1.BluehengeService/UpdateSession',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.UpdateSessionRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.UpdateSessionResponse.FromString,
                _registered_method=True)
        self.StreamASR = channel.stream_unary(
                '/cobaltspeech.bluehenge.v1.BluehengeService/StreamASR',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamASRRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamASRResponse.FromString,
                _registered_method=True)
        self.StreamTTS = channel.unary_stream(
                '/cobaltspeech.bluehenge.v1.BluehengeService/StreamTTS',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamTTSRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamTTSResponse.FromString,
                _registered_method=True)
        self.Transcribe = channel.stream_stream(
                '/cobaltspeech.bluehenge.v1.BluehengeService/Transcribe',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.ListProcedures = channel.unary_unary(
                '/cobaltspeech.bluehenge.v1.BluehengeService/ListProcedures',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListProceduresRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListProceduresResponse.FromString,
                _registered_method=True)
        self.GetProcedures = channel.unary_unary(
                '/cobaltspeech.bluehenge.v1.BluehengeService/GetProcedures',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetProceduresRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetProceduresResponse.FromString,
                _registered_method=True)
        self.SaveNote = channel.unary_unary(
                '/cobaltspeech.bluehenge.v1.BluehengeService/SaveNote',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.SaveNoteRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.SaveNoteResponse.FromString,
                _registered_method=True)
        self.GetEntityImage = channel.unary_unary(
                '/cobaltspeech.bluehenge.v1.BluehengeService/GetEntityImage',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetEntityImageRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetEntityImageResponse.FromString,
                _registered_method=True)
        self.GetImage = channel.unary_stream(
                '/cobaltspeech.bluehenge.v1.BluehengeService/GetImage',
                request_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetImageRequest.SerializeToString,
                response_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetImageResponse.FromString,
                _registered_method=True)


class BluehengeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Version(self, request, context):
        """Returns version information from the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """ListModels returns information about the Bluehenge models
        the server can access.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Create a new Bluehenge session. Also returns a list of
        actions to take next.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Delete the session. Behavior is undefined if the given
        TokenData is used again after this function is called.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSession(self, request, context):
        """Process input for a session and get an updated session with
        a list of actions to take next. This is the only method
        that modifies the Bluehenge session state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamASR(self, request_iterator, context):
        """Create an ASR stream. A result is returned when the
        stream is closed by the client (which forces the ASR to
        endpoint), or when a transcript becomes available on its
        own, in which case the stream is closed by the server.
        The ASR result may be used in the UpdateSession method.
        <br/><br/>
        If the session has a wakeword enabled, and the client
        application is using Diatheke and Cubic to handle the
        wakeword processing, this method will not return a
        result until the wakeword condition has been satisfied.
        Utterances without the required wakeword will be
        discarded and no transcription will be returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTTS(self, request, context):
        """Create a TTS stream to receive audio for the given reply.
        The stream will close when TTS is finished. The client
        may also close the stream early to cancel the speech
        synthesis.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request_iterator, context):
        """Create an ASR stream for transcription. Unlike StreamASR,
        Transcribe does not listen for a wakeword. This method
        returns a bi-directional stream, and its intended use is
        for situations where a user may say anything at all, whether
        it is short or long, and the application wants to save the
        transcript (e.g., take a note, send a message).
        <br/><br/>
        The first message sent to the server must be the TranscribeAction,
        with remaining messages sending audio data.
        Messages received from the server will include the current
        best partial transcription until the full transcription is
        ready. The stream ends when either the client application
        closes it, a predefined duration of silence (non-speech)
        occurs, or the end-transcription intent is recognized.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProcedures(self, request, context):
        """It sends an empty request and gets as response a list of all the procedures stored in the knowledge graph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcedures(self, request, context):
        """Gets a single procedure identified by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveNote(self, request, context):
        """Saves a note in a specific step during a procedure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityImage(self, request, context):
        """Gets the data related with an image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Gets a request with an id of the image and sends the image by chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BluehengeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.VersionRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.VersionResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListModelsRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListModelsResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.CreateSessionRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.CreateSessionResponse.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.DeleteSessionRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.DeleteSessionResponse.SerializeToString,
            ),
            'UpdateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSession,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.UpdateSessionRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.UpdateSessionResponse.SerializeToString,
            ),
            'StreamASR': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamASR,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamASRRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamASRResponse.SerializeToString,
            ),
            'StreamTTS': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTTS,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamTTSRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamTTSResponse.SerializeToString,
            ),
            'Transcribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.TranscribeRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.TranscribeResponse.SerializeToString,
            ),
            'ListProcedures': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcedures,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListProceduresRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListProceduresResponse.SerializeToString,
            ),
            'GetProcedures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcedures,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetProceduresRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetProceduresResponse.SerializeToString,
            ),
            'SaveNote': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveNote,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.SaveNoteRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.SaveNoteResponse.SerializeToString,
            ),
            'GetEntityImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityImage,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetEntityImageRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetEntityImageResponse.SerializeToString,
            ),
            'GetImage': grpc.unary_stream_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetImageRequest.FromString,
                    response_serializer=cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cobaltspeech.bluehenge.v1.BluehengeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BluehengeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/Version',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.VersionRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/ListModels',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListModelsRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/CreateSession',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.CreateSessionRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/DeleteSession',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.DeleteSessionRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/UpdateSession',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.UpdateSessionRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.UpdateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamASR(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/StreamASR',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamASRRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamASRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTTS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/StreamTTS',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamTTSRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.StreamTTSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/Transcribe',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.TranscribeRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProcedures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/ListProcedures',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListProceduresRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.ListProceduresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcedures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/GetProcedures',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetProceduresRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetProceduresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/SaveNote',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.SaveNoteRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.SaveNoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntityImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/GetEntityImage',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetEntityImageRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetEntityImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cobaltspeech.bluehenge.v1.BluehengeService/GetImage',
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetImageRequest.SerializeToString,
            cobaltspeech_dot_bluehenge_dot_v1_dot_bluehenge__pb2.GetImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
